### ISSUE TITLE
cli.test_classparameters.test_positive_puppet_default - KeyError: 'use-puppet-default'

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4095] opened 2016-12-15 10:55 UTC
Looks like `hammer --json sc-param info` does not expose the `user-puppet-default` attribute as our test expects:

```bash
2016-12-13 03:00:03 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv sc-param update --override="1" --use-puppet-default="1" --id="210"
016-12-13 03:00:07 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=json sc-param info --puppet-class="ntp" --id="210"
2016-12-13 03:00:10 - robottelo.ssh - DEBUG - <<< stdout
{
  "Id": 210,
  "Parameter": "cli_classparameters_scp_185",
  "Default Value": "Iexei1Ohyo",
  "Override": true,
  "Puppet class": "cli_test_classparameters",
  "Description": null,
  "Type": "string",
  "Hidden Value?": false,
  "Required": false,
  "Validator": {
    "Type": null,
    "Rule": null
  },
  "Override values": {
    "Merge overrides": false,
    "Merge default value": false,
    "Avoid duplicates": false,
    "Order": [
      "fqdn",
      "hostgroup",
      "os",
      "domain"
    ],
    "Values": {
    }
  },
  "Environments": [
    {
      "id": 105,
      "name": "KT_wgOWpv_Library_nYjSxQkUIR_441"
    }
  ],
  "Created at": "2016-12-13 07:58:26 UTC",
  "Updated at": "2016-12-13 08:00:06 UTC"
}
```
```bash
>       self.assertEqual(sc_param['use-puppet-default'], True)
E       KeyError: 'use-puppet-default'
```

**Comment by omaciel** [comment] 2016-12-15 21:17
@rplevka is this a regression on hammer? Has this test ever successfully executed before?

**Comment by rplevka** [comment] 2016-12-16 09:41
@omaciel not sure yet, however, this error seemed to be  just masked by other error we had in our tests.

**Comment by svtkachenko** [comment] 2016-12-16 19:46
Previously on `6.2` it was skipped because of bug but since `6.3.0 Snap 5` bug was fixed for `6.3` only and marked as verified so test started failing. However, since yesterday we have merged new logic for `skip_if_bug_open` and bug is skipped again. So not relevant for `6.2`

**Comment by svtkachenko** [comment] 2016-12-16 19:48
And for `6.3` it looks like the tricky one. It passes on my machine but failing for sure on QE, even when I run test locally/

**Comment by svtkachenko** [comment] 2016-12-20 13:15
With latest `6.3` build passed both locally and on Jenkins.

**Closed by svtkachenko** 2016-12-20 13:15 UTC
Labels: 6.3, CLI, Sprint3 19Dec16
