### ISSUE TITLE
Automation failure : test_update_ptable

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2233] opened 2015-05-14 11:40 UTC
TestNames:
tests.foreman.cli.test_partitiontable.TestPartitionTableUpdateCreate.test_update_ptable

Error Message
Failed to create PartitionTable with {u'os-family': 'Solaris', u'name': u'7b2c4H', u'file': '/tmp/vFm3ekHVCF'} data due to:
  [ERROR 2015-05-13 15:25:16 Exception] Error: Request Timeout
  Could not create the partition table:
    Error: Request Timeout
  [ERROR 2015-05-13 15:25:16 Exception] 
  
  RestClient::RequestTimeout (Request Timeout):
      /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:184:in `rescue in transmit'
      /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:140:in `transmit'
      /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
      /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
      /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
      /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
      /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
      /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
      /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
      /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/apipie/command.rb:43:in `send_request'
      /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
      /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/apipie/command.rb:34:in `execute'
      /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
      /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
      /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
      /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
      /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
      /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
      /usr/share/gems/gems/hammer_cli-0.1.4.10/bin/hammer:108:in `<top (required)>'
      /usr/bin/hammer:23:in `load'
      /usr/bin/hammer:23:in `<main>'

**Comment by tkolhar** [comment] 2015-05-14 11:49
when executed locally using nosetests
$ nosetests -c robottelo.properties -m test_update_ptable /home/tkolhar/git/robottelo/tests/foreman/cli/test_partitiontable.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@Test: Check if Partition Table can be updated ... 2015-05-14 17:10:26 - robottelo - DEBUG - Running test TestPartitionTableUpdateCreate/test_update_ptable
2015-05-14 17:10:29 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1d9b410
2015-05-14 17:10:32 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1d9b410
2015-05-14 17:10:32 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1d9b410
2015-05-14 17:10:32 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv partition-table create --os-family="Gentoo" --name="ufVvTD" --file="/tmp/Nkf4qESLYM"
2015-05-14 17:10:34 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ddae90
2015-05-14 17:10:36 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ddae90
2015-05-14 17:10:36 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ddae90
2015-05-14 17:10:36 - robottelo.common.ssh - DEBUG - <<<
Message,Id,Name
Partition table created,40,ufVvTD

2015-05-14 17:10:36 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  partition-table info --id="40"
2015-05-14 17:10:39 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1d9b590
2015-05-14 17:10:40 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1d9b590
2015-05-14 17:10:41 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1d9b590
2015-05-14 17:10:41 - robottelo.common.ssh - DEBUG - <<<
Id:                40
Name:              ufVvTD
OS Family:         Gentoo
Operating systems: 

Created at:        2015/05/14 11:40:36
Updated at:        2015/05/14 11:40:36


2015-05-14 17:10:41 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv partition-table list --search="name=\"ufVvTD\"" --per-page="10000"
2015-05-14 17:10:43 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ddadd0
2015-05-14 17:10:45 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ddadd0
2015-05-14 17:10:45 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ddadd0
2015-05-14 17:10:45 - robottelo.common.ssh - DEBUG - <<<
Id,Name,OS Family
40,ufVvTD,Gentoo

2015-05-14 17:10:45 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv partition-table update --name="ufVvTD" --new-name="g1xKvF"
2015-05-14 17:10:48 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1d9b750
2015-05-14 17:10:50 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1d9b750
2015-05-14 17:10:50 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1d9b750
2015-05-14 17:10:50 - robottelo.common.ssh - DEBUG - <<<
Message,Id,Name
Partition table updated,40,g1xKvF

2015-05-14 17:10:50 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv partition-table list --search="new-name=\"g1xKvF\"" --per-page="10000"
2015-05-14 17:10:52 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x1ddae50
2015-05-14 17:10:54 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x1ddae50
2015-05-14 17:10:54 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x1ddae50
2015-05-14 17:10:54 - robottelo.common.ssh - DEBUG - <<< [ERROR 2015-05-14 07:40:54 Exception] Error: 400 Bad Request
Error: 400 Bad Request
[ERROR 2015-05-14 07:40:54 Exception] 

RestClient::BadRequest (400 Bad Request):
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /usr/share/ruby/net/http.rb:852:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:270:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:316:in `retrieve_and_print'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:303:in `browse_collection'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:288:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

ok
XML: foreman-results.xml
Ran 1 test in 27.601s
OK

seems to be a bz https://bugzilla.redhat.com/show_bug.cgi?id=1221576
please add the decorator and fix it 
thanks

**Comment by elyezer** [comment] 2015-05-14 14:30
Was not able to reproduce. I have run the same test against the same machine automation did and got no failures. It seems to be some server instability because `[ERROR 2015-05-13 15:25:16 Exception] Error: Request Timeout`.

Will close this issue and be monitoring for that happens again.

```
$ py.test tests/foreman/cli/test_partitiontable.py -ktest_update_ptable
=================================================== test session starts ===================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 6 items

tests/foreman/cli/test_partitiontable.py .

====================================== 5 tests deselected by '-ktest_update_ptable' =======================================
========================================= 1 passed, 5 deselected in 20.19 seconds =========================================
```

**Closed by elyezer** 2015-05-14 14:30 UTC
Labels: CLI, Downstream Failure
