### ISSUE TITLE
cli.test_contenthost.ContentHostTestCase - wrong command usage

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4030] opened 2016-11-24 15:09 UTC
Looks like the command usage might have changed:

```
2016-11-02 20:03:27 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme --output=csv host subscription register --content-view-id="319" --organization-id="387" --name="fqfZBVeUOtTbYSk" --lifecycle-environment-id="303"
2016-11-02 20:03:29 - robottelo.ssh - DEBUG - <<< stderr
[ERROR 2016-11-02 20:03:29 API] 500 Internal Server Error
[ERROR 2016-11-02 20:03:29 Exception] wrong number of arguments (3 for 2)
Failed to register host:
  wrong number of arguments (3 for 2)
[ERROR 2016-11-02 20:03:29 Exception] 

RestClient::InternalServerError (500 Internal Server Error):
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.18/lib/apipie_bindings/api.rb:312:in `block in rest_client_call_block'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    /opt/rh/rh-ruby22/root/usr/share/ruby/net/http.rb:853:in `start'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.8.0/lib/restclient/resource.rb:67:in `post'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.18/lib/apipie_bindings/api.rb:293:in `call_client'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.18/lib/apipie_bindings/api.rb:222:in `http_call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.18/lib/apipie_bindings/api.rb:172:in `call_action'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.18/lib/apipie_bindings/api.rb:167:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.0.18/lib/apipie_bindings/resource.rb:21:in `call'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli_foreman-0.8.0/lib/hammer_cli_foreman/commands.rb:190:in `send_request'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/apipie/command.rb:34:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/bin/hammer:125:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'```

**Comment by rplevka** [comment] 2016-11-24 15:09
affects >= 10 tests [marking Medium]

**Comment by lpramuk** [comment] 2016-11-25 12:12
```POST "/api/hosts/subscriptions"``` is failing with ```ArgumentError: wrong number of arguments (3 for 2)```

I reported this BZ for this issue https://bugzilla.redhat.com/show_bug.cgi?id=1397860

**Comment by abalakh** [comment] 2016-11-25 14:08
A lot of ContentHostTestCase failures may be related to #3939 btw - for 6.3 `content-host` command was removed.

**Comment by rplevka** [comment] 2016-11-25 14:12
@abalakh yeah, i thought the same. However this test uses `hammer host` already.

**Comment by ldjebran** [comment] 2016-12-05 14:34
@lpramuk, @sghai cannot figure out what to do here if all investigations have been done, all bugs registered, there is for instance 4 bugs reported for this:     
https://bugzilla.redhat.com/show_bug.cgi?id=1397860
https://bugzilla.redhat.com/show_bug.cgi?id=1383793
https://bugzilla.redhat.com/show_bug.cgi?id=1400970
https://bugzilla.redhat.com/show_bug.cgi?id=1383793
all the  bugs are duplicate of next till last 1383793, that is flagged 6.2.z+

**Comment by rplevka** [comment] 2016-12-05 14:46
@ldjebran I've added 6.3.0? flag to 1383793 there (i believe it got to be set automatically though)

**Comment by sghai** [comment] 2016-12-05 14:47
@ldjebran : [bz1383793](https://bugzilla.redhat.com/show_bug.cgi?id=1383793) is set of 6.2.5 and in post state (which means fix is ready but not yet in 6.2.5-2). [bz1400970](https://bugzilla.redhat.com/show_bug.cgi?id=1400970) is opened for release 6.3.

So I think we need to just decorate related test case with bz decorator, atleast for 6.3(master branch)

**Comment by ldjebran** [comment] 2016-12-05 15:58
@sghai, @rplevka, the latest 6.3 build 13 snap7 all testcases failed with a new error raised in setupClass:
```bash
CLIReturnCodeError: CLIReturnCodeError(return_code=64, stderr=u"[ERROR 2016-12-01 09:55:17 Exception] Error: Unrecognised option '--organization-id'\n\nSee: 'hammer content-view info --help'\nError: Unrecognised option '--organization-id'\n\nSee: 'hammer content-view info --help'\n[ERROR 2016-12-01 09:55:17 Exception] \n\nClamp::UsageError (Unrecognised option '--organization-id')   
```
install a new build to investigate on

**Comment by ldjebran** [comment] 2016-12-05 16:19
@sghai, @rplevka, it seems that this is the same bug as https://bugzilla.redhat.com/show_bug.cgi?id=1388642
as in issue #4031, but in this we have to decorate  all the class ContentHostTestCase with bz 1388642 and each test in tier1 by bz 1400970
what do you think?

**Comment by sghai** [comment] 2016-12-06 03:24
@ldjebran : Instead of decorating the class with bz id. Let me ask folks to prioritize the bz so that we can get fixes in next 6.3 compose. 
FYI.. If bz is in `post` state that means fix is already merged in upstream but not yet cherry-picked for downstream.

**Comment by sghai** [comment] 2016-12-06 03:33
@ldjebran : lets keep this issue open until next snap results. And no need to decorate all tests. I've already requested @ehelms if we can get the fixes in next compose.

@omaciel @cswiii : Hey, what do you think ?

**Comment by ldjebran** [comment] 2016-12-06 07:35
@sghai think your proposal to accelerate the fix is reasonable, will keep an eye on this issue for the next compose.

**Comment by ldjebran** [comment] 2016-12-13 17:14
same issue on compose 8

**Comment by rplevka** [comment] 2017-02-02 13:24
@sghai ok, we decided to wait for a new snap 2 months ago. I think it's time to decide on an action we'll take :)

**Comment by lpramuk** [comment] 2017-05-05 08:49
the original tests were moved/merged to 
 tests.foreman.cli.test_host.HostCreateTestCase - unfortunatelly for satellite nigthly they failed due to another reason.

**Comment by ntkathole** [comment] 2019-06-06 09:10
Please feel free to re-open, if this still needs fixing.

**Closed by ntkathole** 2019-06-06 09:10 UTC
Labels: 6.3, CLI, Medium Priority, blocked
