### ISSUE TITLE
tests.foreman.api.test_contentaccess.ContentAccessTestCase.test_positive_list_hosts_applicable expects there are some applicable errata to the host, but there are not

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/robottelo#6120] opened 2018-07-04 08:58 UTC
```
<jhutar> dlezz, Hello. I'm investigating https://.../view/Satellite6.4/job/automation-6.4-tier2-rhel7/25/testReport/tests.foreman.api.test_contentaccess/ContentAccessTestCase/test_positive_list_hosts_applicable/ and I do not understand why are we expecting that there should be some applicable errata?
<jhutar> dlezz, I mean: I do not see any packge downgrade or so
<dlezz> jhutar, looking
<dlezz> jhutar, I think the problem here is that this test was done to work with RHEL7.4 but record has been changed to RHEL7Server where all packages already in last state and there is no errata applicable
```

```
self = <tests.foreman.api.test_contentaccess.ContentAccessTestCase testMethod=test_positive_list_hosts_applicable>

    @run_only_on('sat')
    @tier2
    @upgrade
    def test_positive_list_hosts_applicable(self):
        """Request `errata/hosts_applicable` and assert the host with no
            attached subscriptions is present.
    
            :id: 68ed5b10-7a45-4f2d-93ed-cffa737211d5
    
            :steps:
    
                1. Request errata/hosts_applicable for organization created on
                   setUp.
    
            :CaseAutomation: automated
    
            :expectedresults:
                1. Assert the host with no attached subscription is listed to have
                   access to errata content.
    
            :CaseImportance: Critical
            """
        with VirtualMachine(distro=DISTRO_RHEL7) as vm:
            setup_virtual_machine(
                vm,
                self.org.label,
                rh_repos_id=[
                    repo['repository-id'] for repo in self.repos if repo['cdn']
                ],
                product_label=self.custom_product['label'],
                repos_label=[
                    repo['label'] for repo in self.repos_info
                    if repo['red-hat-repository'] == 'no'
                ],
                lce=ENVIRONMENT,
                patch_os_release_distro=DISTRO_RHEL7,
                install_katello_agent=True,
            )
            host = entities.Host(
                name=vm.hostname, organization=self.org).search()[0].read()
            # force host to generate errata applicability
            call_entity_method_with_timeout(
                host.errata_applicability, timeout=600)
            erratum = host.errata()['results']
>           self.assertGreater(len(erratum), 0)
E           AssertionError: 0 not greater than 0

tests/foreman/api/test_contentaccess.py:171: AssertionError
```

**Comment by pondrejk** [comment] 2018-08-16 08:36
This no longer fails in automation, and I'm not able to reproduce locally, though I didn't find which commit came with the fix, anyways, closing for now

**Closed by pondrejk** 2018-08-16 08:36 UTC
Labels: 6.4

**Comment by jhutar** [comment] 2018-10-15 13:09
Great!
