### ISSUE TITLE
test_docker.py:test_positive_delete: installed package conflict

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4019] opened 2016-11-23 17:25 UTC
the installation of the `katello-ca-consumer` package fails due to another version of the package already installed (katello consumer from another satellite):

```
2016-11-02 19:55:35 - robottelo.ssh - DEBUG - <<< stdout
Retrieving http://qe-sat63-rhel7.com/pub/katello-ca-consumer-latest.noarch.rpm
Preparing...                          ########################################

2016-11-02 19:55:35 - robottelo.ssh - DEBUG - <<< stderr
	file /usr/bin/katello-rhsm-consumer from install of katello-ca-consumer-qe-sat63-rhel7.satqe.lab.eng.rdu2.redhat.com-1.0-1.noarch conflicts with file from package katello-ca-consumer-dogfood-satellite.com-1.0-1.noarch

2016-11-02 19:55:35 - robottelo.ssh - INFO - Destroying Paramiko client 0x7fa80f4c08d0
```

**Comment by lpramuk** [comment] 2016-11-25 08:38
it has to be that way if we use AK method to install Satellite.
Yet another argument for switching from AK over to REPOFILE method to install Satellite.

We should re-consider using AK installation.

**Comment by lpramuk** [comment] 2016-11-25 08:43
Or for containers created using CVs we should use another machine (not a Satellite) as a docker host (and avoid Satellite self-registering)

For containers created using dockerhub/ext registries it is OK to use Satellite as a docker host. (no need for self-registering)

**Comment by rplevka** [comment] 2016-11-25 09:32
@lpramuk would you mind filing a `robottelo-ci` issue referring to this issue?

**Comment by lpramuk** [comment] 2017-05-05 08:34
duplicate of #4401

**Closed by lpramuk** 2017-05-05 08:34 UTC
Labels: 6.3, API, test-failure
