### ISSUE TITLE
[py3.6] TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5888] opened 2018-03-28 10:43 UTC
TypeError: write() argument must be str, not bytes

tests.foreman.api.test_repository/RepositoryTestCase/test_positive_access_protected_repository

**Comment by ldjebran** [comment] 2018-03-28 14:08
@rplevka The returned certificate from nailgun is byte in py3, so perhaps we have to update the nailgun download_debug_certificate  to always return str

**Comment by rplevka** [comment] 2018-03-28 14:14
@ldjebran yeah, thanks for looking into this. yeah, this was just a placeholder issue, so i guess let's open up a nailgun one and keep it referenced

**Comment by jhutar** [comment] 2018-03-29 08:45
Created PR https://github.com/SatelliteQE/nailgun/pull/485 with this change. I was unable to run the test because mine Sat is hand-installed so `requests.exceptions.SSLError: HTTPSConnectionPool(host='sat630.example.com', port=443): Max retries exceeded with url: /pulp/repos/fksCpkEtnjvN/Library/custom/bQASRMxJp/jlbvdiCh/repodata/repomd.xml (Caused by SSLError(SSLError(336445449, '[SSL] PEM lib (_ssl.c:3405)'),))`. I assume that is because of mine config.

**Comment by ldjebran** [comment] 2018-03-29 09:53
@jhutar no the problem was about the saved saved value that was not correctly returned as we should use decode('utf-8') 

Think it seems to be more complicated to resolve that on nailgun perhaps fix the test to decode that returned value will be the simplest way to resolve this issue.
```python
...
        with self.assertRaises(SSLError):
            client.get(repo_data_file_url, verify=False)
        # get the organization debug certificate
        cert_content = self.org.download_debug_certificate().decode('utf-8')
        # save the organization debug certificate to file
        cert_file_path = '{0}/{1}.pem'.format(
            tempfile.gettempdir(), self.org.label)
        with open(cert_file_path, 'w') as cert_file:
            cert_file.write(cert_content)
        # access repository data with organization debug certificate
        response = client.get(
            repo_data_file_url, cert=cert_file_path, verify=False)
...
```
This should work in python 2 and python 3

**Comment by lpramuk** [comment] 2018-03-29 14:47
+1 couple of similar issues were solved by adding ```.decode('utf-8')```

**Comment by jhutar** [comment] 2018-03-29 22:22
Cool. It works with the fix you both proposed in the Nailgun PR:
```
$ py.test tests/foreman/api/test_repository.py::RepositoryTestCase::test_positive_access_protected_repository
============================= test session starts ==============================
platform linux -- Python 3.6.4, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/pok/Checkouts/robottelo, inifile:
plugins: services-1.2.1, mock-1.6.3
collected 1 item
2018-03-30 00:12:46 - conftest - DEBUG - Collected 1 test cases


tests/foreman/api/test_repository.py .                                   [100%]

============================== 0 tests deselected ==============================
========================== 1 passed in 47.34 seconds ===========================
```

**Comment by jhutar** [comment] 2018-04-03 15:50
https://github.com/SatelliteQE/nailgun/pull/485 merged, so we are good here.

**Closed by jhutar** 2018-04-03 15:51 UTC
Labels: 6.2, 6.3, 6.4, High, test-failure
