### ISSUE TITLE
Automation Failure smoke test : TestSmoke.test_end_to_end

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2120] opened 2015-04-24 07:25 UTC
Test results for sat6 GA snap1

Testnames:
tests.foreman.smoke.test_api_smoke.TestSmoke.test_end_to_end

the test is failing becoz of:
   "The length of the results is:", len(results))
'(\'The length of the results is:\', 0)

please fix this
thanks

**Comment by JacobCallahan** [comment] 2015-04-30 20:37
The issues related to this test seem to have been resolved. Are you able to reproduce?

**Comment by elyezer** [comment] 2015-05-04 14:22
Smoke is green again, that was due to a build failure. Closing this.

**Closed by elyezer** 2015-05-04 14:22 UTC
Labels: API, Downstream Failure
