### ISSUE TITLE
Bugzilla Proxy Error

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4100] opened 2016-12-16 14:01 UTC
When we started to used authenticated account this 502 Proxy Error for url of Bugzilla appeared once only.
We'll be watching for occurences.

```
robottelo/decorators/__init__.py:446: in wrapper_func
    if self.bug_type == 'bugzilla' and bz_bug_is_open(self.bug_id):
robottelo/decorators/__init__.py:367: in bz_bug_is_open
    bug = _get_bugzilla_bug(bug_id)
robottelo/decorators/__init__.py:279: in _get_bugzilla_bug
    _bugzilla[bug_id] = bz_conn.getbugsimple(bug_id)
../../shiningpanda/jobs/fed67494/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py:1051: in getbugsimple
    dict=self._getbug(objid, simple=True),
../../shiningpanda/jobs/fed67494/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py:1023: in _getbug
    extra_fields=extra_fields)[0]
../../shiningpanda/jobs/fed67494/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py:995: in _getbugs
    r = self._proxy.Bug.get(getbugdata)
/usr/lib64/python2.7/xmlrpclib.py:1240: in __call__
    return self.__send(self.__name, args)
../../shiningpanda/jobs/fed67494/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py:168: in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
/usr/lib64/python2.7/xmlrpclib.py:1599: in __request
    verbose=self.__verbose
../../shiningpanda/jobs/fed67494/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py:259: in request
    return self._request_helper(url, request_body)
../../shiningpanda/jobs/fed67494/virtualenvs/d41d8cd9/lib/python2.7/site-packages/bugzilla/base.py:236: in _request_helper
    response.raise_for_status()
```
```
self = <Response [502]>

    def raise_for_status(self):
        """Raises stored :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ''
    
        if 400 <= self.status_code < 500:
            http_error_msg = '%s Client Error: %s for url: %s' % (self.status_code, self.reason, self.url)
    
        elif 500 <= self.status_code < 600:
            http_error_msg = '%s Server Error: %s for url: %s' % (self.status_code, self.reason, self.url)
    
        if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           HTTPError: 502 Server Error: Proxy Error for url: https://bugzilla.redhat.com/xmlrpc.cgi
```

**Comment by rplevka** [comment] 2016-12-16 14:18
This comment: https://bugzilla.redhat.com/show_bug.cgi?id=1275422#c1 indicates that the error might be caused by huge load of data requested.
Perhaps we should see which request has caused this and try to optimize the query?

**Comment by lpramuk** [comment] 2016-12-16 14:26
in that BZ it timeouted during getting of products 
```
    ret = self._proxy.Product.get(kwargs)
```
while we timeouted? during getting of bugdata, humm
```
 r = self._proxy.Bug.get(getbugdata)
```

**Comment by rplevka** [comment] 2018-10-03 13:09
this never reoccurred again. closing

**Closed by rplevka** 2018-10-03 13:09 UTC
Labels: Bug, test-failure
