### ISSUE TITLE
Automation failure : test_sync_rh_repos

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2253] opened 2015-05-18 11:07 UTC
TestNames:
tests.foreman.ui.test_sync.Sync.test_sync_rh_reposError Message

Error
Could not select the product: 'Red Hat Enterprise Linux Server'
-------------------- >> begin captured logging << --------------------
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x46cf610
robottelo.common.ssh: INFO: Destroying Paramiko client 0x46cf610
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x46cf610
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
robottelo.ui.locators: DEBUG: Accessing locator "menu.any_context" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "org.nav_current_org" by xpath: "(//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]//li/a[@data-toggle='dropdown'])[1]"
robottelo.ui.locators: DEBUG: Accessing locator "org.select_org" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@href='/organizations/clear']/../../li/a[contains(.,'%s')]"
robottelo.ui.locators: DEBUG: Accessing locator "menu.current_text" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//li[contains(@class,'org-switcher')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.fetch_org" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//li[contains(@class, 'org-menu')]/a"
robottelo.ui.locators: DEBUG: Accessing locator "menu.content" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.red_hat_subscriptions" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_red_hat_subscriptions']"
robottelo.ui.locators: DEBUG: Accessing locator "subs.manage_manifest" by xpath: "//button[contains(@ui-sref,'manifest.import')]"
robottelo.ui.locators: DEBUG: Accessing locator "subs.file_path" by xpath: "//input[@name='content']"
robottelo.ui.locators: DEBUG: Accessing locator "subs.upload" by xpath: "//div[@class='form-group']/button[contains(@class, 'primary')]"
robottelo.ui.locators: DEBUG: Accessing locator "subs.manifest_exists" by xpath: "//a[contains(@href,'distributors')]"
robottelo.ui.base: DEBUG: TimeoutException: Timed out waiting for element '//a[contains(@href,'distributors')]' to display.
robottelo.ui.locators: DEBUG: Accessing locator "menu.content" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='content_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.red_hat_repositories" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_redhat_provider']"
robottelo.ui.locators: DEBUG: Accessing locator "rh.prd_expander" by xpath: "//div[@id='ui-tabs-1']//td[contains(.,'%s')]/span[@class='expander']"
robottelo.ui.locators: DEBUG: Accessing locator "rh.reposet_expander" by xpath: "//span[@class='expander_area' and contains(.,'%s')]/span"
robottelo.ui.locators: DEBUG: Accessing locator "rh.reposet_checkbox" by xpath: "//span[@class='expander_area' and contains(.,'%s')]/../../td/input[@class='repo_set_enable']"
robottelo.ui.locators: DEBUG: Accessing locator "rh.repo_checkbox" by xpath: "//table[@class='repo_table']//td[contains(.,'%s')]/../td/label/input[@class='repo_enable']"
robottelo.ui.locators: DEBUG: Accessing locator "rh.reposet_spinner" by xpath: "//span[@class='expander_area' and contains(.,'%s')]/../../td/img[@alt='Spinner']"
robottelo.ui.locators: DEBUG: Accessing locator "rh.repo_spinner" by xpath: "//table[@class='repo_table']//td[contains(.,'%s')]/../td/label/img[@alt='Spinner']"
robottelo.ui.base: DEBUG: TimeoutException: Timed out waiting for element '//div[@id='ui-tabs-1']//td[contains(.,'Red Hat Enterprise Linux Server')]/span[@class='expander']' to display.

**Comment by sghai** [comment] 2015-05-18 11:11
Closed as duplicate of #2156

**Comment by tkolhar** [comment] 2015-05-18 11:11
when executed locally using nosetests : 
$  nosetests -c robottelo.properties -m test_sync_rh_repos /home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py
ERROR
ERROR: @Test: Create Content RedHat Sync with two repos.

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_sync.py", line 81, in test_sync_rh_repos
    self.subscriptions.upload(manifest_path)
  File "/home/tkolhar/git/robottelo/robottelo/ui/subscription.py", line 23, in upload
    self.wait_until_element(locators["subs.manage_manifest"]).click()
AttributeError: 'NoneType' object has no attribute 'click'


ERROR: @Test: Create Content RedHat Sync with two repos.

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 256, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 244, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
XML: foreman-results.xml
Ran 1 test in 58.843s
FAILED (errors=2)

it seems path has no defined object . please fix it thanks

**Closed by sghai** 2015-05-18 11:11 UTC
Labels: Downstream Failure, UI
