### ISSUE TITLE
UI HostContentHostUnificationTestCase - failing host rename test cases

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5598] opened 2017-11-20 12:01 UTC
the following test cases have been failing long-term and need some care:

- test_positive_rename_content_host
- test_positive_rename_content_host_cli
- test_positive_rename_foreman_host

**Comment by rplevka** [comment] 2017-12-07 15:19
- test_positive_rename_foreman_host keeps failing

test_positive_rename_content_host
and
test_positive_rename_content_host_cli

passed for 3 builds but then started to fail again

**Comment by odovzhenko** [comment] 2017-12-08 12:25
test_positive_rename_content_host and test_positive_rename_content_host_cli passed for m locally and in Sauce Labs. Probably some random issue. For test_positive_rename_foreman_host I opened #5662 for further investigation.

**Comment by odovzhenko** [comment] 2018-01-22 10:33
Closed as duplicate of #5662

**Closed by odovzhenko** 2018-01-22 10:33 UTC
Labels: Medium, test-failure
