### ISSUE TITLE
tests.foreman.cli.test_hammer.HammerCommandsTestCase.test_positive_all_options (from tier1-parallel) - AssertionError

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/robottelo#6914] opened 2019-05-13 06:13 UTC
self = <tests.foreman.cli.test_hammer.HammerCommandsTestCase testMethod=test_positive_all_options>

    @tier1
    @upgrade
    def test_positive_all_options(self):
        """check all provided options for every hammer command
    
        :id: 1203ab9f-896d-4039-a166-9e2d36925b5b
    
        :expectedresults: All expected options are present
    
        :CaseImportance: Critical
        """
        self.maxDiff = None
        self._traverse_command_tree()
        if self.differences:
            self.fail(
>               '\n' + _format_commands_diff(self.differences)

**Comment by devendra104** [comment] 2019-05-28 06:27
This issue is a duplicate of #6942.

**Closed** 2019-05-28 06:41 UTC
Labels: CLI, test-failure
