### ISSUE TITLE
Tests naming conventions

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#3083] opened 2015-11-26 09:31 UTC
Here we like to describe some rules that should be used when we name our tests in our development. All of them, of course, cannot be applied for each and every situation, but, anyway, should be treated as generic template.

**All tests**
- Should be started from word `test` (`test_xxxxxxxx`)
- `positive` or `negative` term should be used as second word (`test_positive_xxxxxxxx` or `test_negative_xxxxxxxx`)

**First Tier**
- Test name should always contain one from `create`, `update` or `delete` terms as third word (`test_postive_create_xxxxxxxx` or `test_negative_update_xxxxxxxx`)

**Second Tier**
- Test name should contain action that is planned to be performed as third word (`test_positive_publish_xxxxxxxx` or `test_negative_add_xxxxxxxx``)

**Third Tier**
- Same as for tier two, but also can contain words like `long`, `end-to-end` or `infrastructure`.

**General requirements**
- After these three words we should briefly describe goal of particular test (`test_positive_publish_composite_cv` or `test_positive_associate_custom_content`). That can help in further test failures analyze procedure as it is easier to remember precise names
- We do not need to specify feature under test in a test name (for example, state `test_positive_cv_promote` explicitly for `test_content_view.py` module as it is already obvious that we are testing content view functionality and use `test_positive_promote` instead)
- Do not use numbers to specify amount of tests in corresponding direction (e.g. `test_positive_create_1` or `test_negative_add_15`)
- There is an exception for cases that are testing specific Bugzilla issue as we can use `test_verify_bugzilla_xxxxxxxx` as a test name

**Comment by sghai** [comment] 2015-11-26 09:53
Awesome.. :+1:

**Comment by abalakh** [comment] 2015-11-26 11:06
:+1:

**Comment by elyezer** [comment] 2015-11-26 11:16
For first tier, we should elect one parameter to be tested. Most of the cases this will be name and will create a tier1 set of tests like: `test_positive_create_name`, `test_positive_update_name` and `test_positive_delete_name`. Other parameters, for example, description, label, etc for that same entity should be marked as being tier 2.

Also I'm wondering if we should s/positive/pos and s/negative/neg. What do you think?

**Comment by oshtaier** [comment] 2015-11-26 11:20
I am fine with that. Let's wait for other people review/suggestions. And especially @omaciel :)
Regarding tiers - as far as I understand, we don't have final solution about test distribution at that moment. If it will be as you described - we should definitely mention that in current issue

**Comment by omaciel** [comment] 2015-11-27 15:26
Hey @SatelliteQE/robottelo-automation !

Taking a little break from all the turkey eating going on around here to chime in on this issue :)

![turkey](http://www.reactiongifs.com/r/tom1.gif)

So, I agree with everything said here and I want to thank @oshtaier for jotting it all down! Since I proposed my definition for the different tiers, I have spent a good chunk of my time thinking about what I said earlier about `tier1` tests. Originally I had said:

>> Tier1: a very basic, CRUD **only** subset that should only test one permutation of actions for a given entity. In other words, even though one can write `create` tests that tests all possible attributes for an `Entity`, I proposed that we pick only one attribute (`name` since it should apply to most entities) and mark these as `@tier1`. All other permutations would be `@tier2`

Having spent a lot of my time going over all of the API and CLI modules, I came to the following conclusion:

* Categorizing tests is **hard** :)
* **Basic** CRUD tests, no matter what the permutations are, is important to determine if the build is good or not, or if there are any regressions
* **Basic** CRUD tests should be very quick to run, since there are no associations required, for most of the cases
* **Tier1** test cases are supposed to tell us, preferably **very fast**, if something is 'wrong' with a build, so, wouldn't we want to know if:
    * Repositories can be synchronized?
    * Content Views can be published and promoted?

So, remember what I said about how categorizing tests is hard? Well, as far as what should be categorized as `Tier1`, how about we do the following:

* **All** permutations of CRUD are by definition `Tier1`
    * This means the test has to **create** the entity with all the required arguments ready.
    * If other entities are added or removed from said entity **after** the entity is created, then we would label these as **association** tests and should be named as `test_positive/negative_associate_*`. These should be categorized as **Tier2** tests.
    * It will be a bit tricky to tell `associate` tests from `update` tests... we will have to do the best that we can here to make a good call

I know that by including the bulk of existing CRUD tests we will be 'slowing down' our runtime but perhaps after a couple of builds we can go over the test results on Jenkins and see which tests take more than a certain amount of time (30 seconds?) and move them to **Tier2**?

This will be a learning experience for all of us, and I don't expect that we will get it right right off the bat, but we can take this as an opportunity to improve our processes.

What do you say???

**Comment by omaciel** [comment] 2015-11-30 15:32
@oshtaier @sthirugn @elyezer @abalakh @sghai @kbidarkar @JacobCallahan @jyejare @cswiii  ???

**Comment by sthirugn** [comment] 2015-12-01 22:38
I am okay with calling all CRUD as tier1 and the CRUD involving associations test as tier 2.

**Comment by omaciel** [comment] 2015-12-02 01:08
Thanks @sthirugn

**Comment by cswiii** [comment] 2015-12-02 13:38
Agree with most of what has been said here already. 

An initial set of CRUD tests should be tier1, cases which exercise pass/fail of core functionality.  Deeper variations can probably be moved to tier2 -- and yes, it will be a bit of trial and error, at least in the beginning, to see how things should be sliced and diced.

From a UI perspective, I sort of picture it as layers based on the menu items. Whatever can be CRUD'ed (!?) on the first view of any menu item is the first thing a user would see/try to use.  These sort of come to my mind, anyway, as tier 1 targets.

Of course, CLI and API are not so easily visualized.

**Comment by omaciel** [comment] 2015-12-02 17:39
**PENDING**

Proposed nomenclature after meeting with @elyezer @abalakh @oshtaier @sthirugn 

Entities abbreviations

| Entity | Singular | Plural |
| ------ | -------- | ------ |
| Content View | cv | cvs |
| Content View Filter | cvf | cvfs |
| Content View Version | cvv | cvvs |
| Repository | repo | repos |
| Organization | org | orgs |
| User | user | users |
| Location | loc | locs |
| Activation Key | ak | aks |
| Content Host | ch | chs |
| Operating System | os | oses |
| Architecture | arch | arches |
| Host | host | hosts |
| Lifecycle Environment | lce | lces |
| Environment (puppet) | env | envs |
| GPG Key | gpg | gpgs |
| Partition Table | ptable | ptables |
| Provisioning Template | template | templates |
| Host Group | hostgroup | hostgroups |
| Compute Resource | compresource | compresources |
| Capsule | capsule | capsules |
| Domain | domain | domains |
| Subnet | subnet | subnets |
| Realm | realm | realms |
| Compute Profile | profile | profiles |
| Installation Media | media | medium |
| Registry | registry | registries |


* test_
  * positive_
  * negative_
    * create_
      * composite
    * update_
    * delete_
    * add_
        * repo
        * cv
        * repos
        * cvs
    * remove_
        * repo
        * cv
        * repos
        * cvs
    * synchronize_
    * promote_
      * with_
      * by_
        * name
        * description
        * label


Examples:

For Organizations:
* @tier1 def test_positive_create_with_name
* @tier1 def test_positive_create_with_description
* @tier1 def test_positive_create_with_label
* @tier1 def test_positive_delete_by_name (UI)
* @tier1 def test_positive_delete_by_id (CLI)
* @tier1 def test_positive_update_name
* @tier2 def test_positive_add_location
* @tier2 def test_positive_remove_location

For Products:
* @tier1 def test_positive_create_with_name
* @tier2 def test_positive_add_{yum,puppet,doker}_repo
* @tier2 def test_positive_add_{yum,puppet,doker}_repos

For Repositories:
* @tier1 def test_positive_create_with_name
* @tier1 def test_positive_create_{yum,puppet,doker}
* @tier2 def test_positive_synchronize_{yum,puppet,doker}

For Content Views:
* @tier1 def test_positive_create_with_name
* @tier1 def test_positive_create_with_{yum,puppet,docker} (**@tier2** for **UI** only!)
* @tier1 def test_positive_create_composite_with_name
* @tier2 def def test_positive_add_{yum,puppet,docker}
* @tier2 def def test_positive_remove_{yum,puppet,docker}
* @tier2 def test_positive_publish_{once,multiple}
* @tier2 def test_positive_promote_{once,multiple}

For Locations:

* @tier1 def test_positive_create_with_users
* @tier2 def test_positive_add_users

* @tier1 def test_positive_update_users

```python
user = create_users_dang_it()
# Create with a user
loc = create_location(users=user)

users = create_users_dang_it()
# Update users
loc.update(users=users)
```

For Hosts:
* @tier1 def test_positive_update_domain

```python
# A domain will be created automatically
host = create_host()

new_domain = create_domain()
host.update(domains=new_domain()
```

**Comment by rplevka** [comment] 2015-12-03 10:20
ACK

**Comment by sghai** [comment] 2015-12-03 10:30
All abbreviations looks good though I've a suggestion if we can call following two entities like:

| Content Host | chost | chosts |
| Lifecycle Environment | lcenv | lcenvs |

**Comment by oshtaier** [comment] 2015-12-03 10:36
@sghai fixed chost as it seems more logical. Regarding Lifecycle Environment - even quick search shows that lcenv (0 occurences) and lce(113 occurences), so I think we should go with lce

**Comment by sghai** [comment] 2015-12-03 10:47
@oshtaier : ah. then we should stick with lce. thanks for checking that..

**Comment by jyejare** [comment] 2015-12-03 11:32
ALL GOOD ! ACK !

**Comment by rplevka** [comment] 2015-12-03 11:47
Wouldn't it be good if we set up a wiki page with information like this?

**Comment by omaciel** [comment] 2015-12-03 20:18
@rplevka yes! I shall move this over internally once we are all in agreement here. Thanks for the suggestion

**Comment by cswiii** [comment] 2015-12-03 20:24
ACK

**Comment by rplevka** [comment] 2015-12-04 08:17
@omaciel: I mean wiki here on github
![github wiki](http://i.imgur.com/PPzbgvr.png)

**Comment by elyezer** [comment] 2015-12-04 13:04
I think is better to use our docs, since there is the place where we provide information about the framework.

**Comment by rplevka** [comment] 2015-12-04 16:35
@elyezer :+1:

**Comment by oshtaier** [comment] 2015-12-07 09:17
@omaciel @elyezer @abalakh @sthirugn 
What's about screenshot functionality? Even now we can get bunch of tests under `test_positive_create` folder. In case, we are going to proceed with strategy described above, we have to not forget about that. Please, correct me if I wrong

**Comment by abalakh** [comment] 2015-12-07 09:32
@oshtaier good point. imo we just need to update our `take_screenshot()` method to create `ClassName/TestName/` dirs, or at least `ClassName.TestName` dir. Voting for a separate issue to update `take_screenshot()` :)

**Comment by omaciel** [comment] 2015-12-07 16:52
@oshtaier definitely need a separate issue for this.

**Comment by oshtaier** [comment] 2015-12-08 08:39
Created new issue for that purpose - https://github.com/SatelliteQE/robottelo/issues/3115

**Comment by sthirugn** [comment] 2015-12-16 19:53
Is there an abbreviation for `host collection` yet?

**Comment by sthirugn** [comment] 2015-12-21 16:03
I came across a negative test case in which content view filter is being created with out providing type.  So I am proposing `test_negative_create_without_type`.  Any objections?

**Comment by elyezer** [comment] 2015-12-21 16:56
@sthirugn sounds good to me.

**Comment by sthirugn** [comment] 2015-12-21 17:54
new acronym - `Composite Content View - ccv`

**Comment by sthirugn** [comment] 2015-12-21 19:59
I have a test case to check `docker image displays tags information for a docker image`.  I have named it `test_positive_read_tags`

**Comment by oshtaier** [comment] 2015-12-21 20:07
@sthirugn All your comments sounds pretty good. Thanks

**Comment by sthirugn** [comment] 2015-12-22 21:05
Looks like this is all addressed now. Closing the issue.

**Closed by sthirugn** 2015-12-22 21:05 UTC
Labels: Infrastructure
