### ISSUE TITLE
make_capsule() doesn't work on RHEL7

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#3453] opened 2016-05-13 07:45 UTC
looks like the the tunnel is being created, but there's an error on accessing the capsule on new port - `Permission denied`. Looks like it is caused by `SELinux` as `setenforce 0` helps.

**Comment by sthirugn** [comment] 2016-05-13 12:36
is this happening due to the pending PR https://github.com/SatelliteQE/automation-tools/pull/330.  If so, we need to get this merged asap <- @elyezer

**Comment by elyezer** [comment] 2016-05-16 13:04
Yes the failures is because firewall. Let's manage to merge that PR. I have some ideas on how to work with firewalld, will work on that asap.

**Comment by lpramuk** [comment] 2016-07-28 13:15
This issue is caused by selinux policy preventing passenger to connect to ports not labeled as websm_port_t (9090/tcp)
```
foreman.te:
allow passenger_t websm_port_t:tcp_socket name_connect;
```
We are going to fix it by labeling predefined range of ports (9091-9190) as websm_port_t ports. 
Plus we dont need ssh for tunneling instead we will switch to use ```socat``` tool

- /me will prepare automation-tools fab task setup_alternate_capsule_ports() superceding enable_gateway_ports()
- @rplevka will make changes to robottelo tests implementing get_alternate_capsule_port()

**Closed** 2016-08-02 12:14 UTC
Labels: Bug, in progress, Infrastructure, Urgent
