### ISSUE TITLE
UI SmartClassParametersTestCase fails with AttributeError: 'SmartClassParameters' object has no attribute 'parameter'

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4596] opened 2017-04-24 10:11 UTC
Whole class with 26 tests failed. 
These tests were run for the 1st time. I don't like failing first-timers as it could indicate we neglect testing prior PR merge.

```
        with Session(self.browser):
            initial_value = self.sc_parameters.fetch_default_value(
>               sc_param.parameter, self.puppet_class.name)
E           AttributeError: 'SmartClassParameters' object has no attribute 'parameter'

tests/foreman/ui/test_classparameters.py:410: AttributeError
```

More interesting is this:
```
2017-04-23 02:31:03 - robottelo.ui.base - DEBUG - Updating field:login.password with:changeme
2017-04-23 02:31:03 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2017-04-23 02:31:06 - robottelo.ui.locators - DEBUG - Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"0
17-04-23 02:31:07 - robottelo.ui.base - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')]: Message: Unable to locate element: {"method":"xpath","selector":"//div[contains(@class, 'jnotify-notification-error')]"}
```

**Comment by oshtaier** [comment] 2017-04-24 10:16
Put corresponding labels

**Comment by oshtaier** [comment] 2017-04-24 10:31
I understand your concerns, but believe me, functionality was tested thoroughly. I had at least 50 runs before submitting the code, so try to avoid assumptions like that

Taking latest code directly from repository - `git checkout upstream/6.2.z`
And running on latest 6.2.9 that installed around 5 days ago:
for example: `test_positive_override_checkbox`
```
nosetests tests/foreman/ui/test_classparameters.py -m test_positive_override_checkbox
.
----------------------------------------------------------------------
Ran 1 test in 116.044s

OK
```
full log - http://pastebin.test.redhat.com/477730

**Comment by lpramuk** [comment] 2017-04-24 10:37
Alex, that is really strange. 
Then it's better to run it in Standalone Automation to avoid diffs between your and jenkins' environment.

**Comment by oshtaier** [comment] 2017-04-24 10:39
Re-tested on Jenkins environment
RHEL6:
http://pastebin.test.redhat.com/477737
RHEL7:
http://pastebin.test.redhat.com/477738

**Comment by oshtaier** [comment] 2017-04-24 10:41
I don't have any diffs between my env and github repository as I took code directly from it. Hmm. That is weird

**Comment by lpramuk** [comment] 2017-04-24 10:45
The only diff is the load ;)
Did the tests fail to login?

**Comment by svtkachenko** [comment] 2017-04-24 10:58
Gentlemen, please keep calm. There is indeed difference in the `6.2` and `6.3` code but on the nailgun side. `nailgun/6.2.z` does not have parameter `parameter` because this field was added in 6.3

**Comment by oshtaier** [comment] 2017-04-24 10:59
I thought that it can be an issue with `production` environment or that puppet classes were not imported or   necessary smart class parameters were not present, but there are all 200 parameters present
```
2017-04-23 01:36:56 - nailgun.client - DEBUG - Making HTTP GET request to https://rhel6/api/v2/smart_class_parameters with options {'verify': False, 'data': '{"per_page": 1000, "search": "puppetclass=\\"ui_test_classparameters\\""}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
2017-04-23 01:36:57 - nailgun.client - DEBUG - Received HTTP 200 response: {
  "total": 3794,
  "subtotal": 200,
  "page": 1,
  "per_page": 1000,
  "search": "puppetclass=\"ui_test_classparameters\"",
  "sort": {
    "by": null,
    "order": null
  },
  "results":
```
and they are like:
```
{"description":null,"override":false,"parameter_type":"string","default_value":"neeNg4Aphu","hidden_value?":false,"hidden_value":"*****","use_puppet_default":null,"required":false,"validator_type":null,"validator_rule":null,"merge_overrides":false,"merge_default":false,"avoid_duplicates":false,"override_value_order":"fqdn\nhostgroup\nos\ndomain","created_at":"2017-04-23 05:36:50 UTC","updated_at":"2017-04-23 05:36:50 UTC","puppetclass_name":"ui_test_classparameters","parameter":"ui_test_classparameters_scp_004","id":1240,"puppetclass_id":76,"override_values_count":0}
```

so we can see in `"parameter":"ui_test_classparameters_scp_004"` that `'parameter'` is a valid attribute

We getting list of all these parameters and doing `pop()` to get single parameter to work with. And it is definitely should have it

**Comment by oshtaier** [comment] 2017-04-24 11:00
And we running all tests in `@run_in_one_thread`, so load should not affect tests themselves

**Comment by oshtaier** [comment] 2017-04-24 11:06
found root cause. Gonna submit fix in nearest hour

**Comment by lpramuk** [comment] 2017-04-24 11:15
Oh I thought testing was against 6.2....

**Comment by oshtaier** [comment] 2017-04-24 11:19
Addressed in https://github.com/SatelliteQE/nailgun/pull/403

**Comment by oshtaier** [comment] 2017-04-24 11:22
`NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')]...` is an error which is present for more than 2 years. Just in case =)

**Comment by abalakh** [comment] 2017-04-24 11:29
@oshtaier @lpramuk it's not even an error - after authenticating we're checking whether any error message is present (to ensure we logged in successfully), this log message basically says 'no errors were present after logging in' (although i have to admit the message itself is very confusing and we should probably improve it)

**Closed** 2017-04-24 11:36 UTC
Labels: 6.2, test-failure, UI
