### ISSUE TITLE
Create test targeting BZ 1232839

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/robottelo#2466] opened 2015-06-18 07:47 UTC
It is necessary to create test that will follow steps mentioned in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1232839

Custom product might be created through API, but all other steps should be performed using UI component. Make sure that valid YUM repo is used in a test

**Comment by jyejare** [comment] 2015-06-30 09:08
I believe this bug is duplicate of bug BZ1225740, and the test for this bug is already added in tests/foreman/ui/test_repository.py file as 'test_discover_repo_1'. And Hence I believe it is not required to add new test for this BZ.

Also the BZ1225740 is currently in New state, and hence the execution of 'test_discover_repo_1' is skipped.

**Comment by oshtaier** [comment] 2015-06-30 11:20
I would say that BZ1225740 is more duplicate as created later, but anyway could @jyejare and @omaciel please, discuss which of this defect should be left, so we can proceed with analysis from test automation perspective further?

**Comment by elyezer** [comment] 2015-07-07 02:05
Any update on this?

**Comment by omaciel** [comment] 2015-07-07 17:54
Thank you @jyejare for filing the BZ and @oshtaier for getting folks to look at it :) I have closed the BZ I filed as a duplicate of the one filed by @jyejare . I also believe that we have this properly automated and will close the issue as there's nothing else left to do here.

Great job everyone! :100:

**Closed by omaciel** 2015-07-07 17:54 UTC
Labels: UI

**Comment by elyezer** [comment] 2015-07-08 18:23
:+1:
