### ISSUE TITLE
Automate this bz : bz id : 1214658

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2129] opened 2015-04-27 06:56 UTC
please automate
- https://bugzilla.redhat.com/show_bug.cgi?id=1214658

hammer content-view  version list
[Foreman] Username: admin
[Foreman] Password for admin: 
undefined method `pulp_id' for nil:NilClass

please automate this
thanks

**Comment by tkolhar** [comment] 2015-04-28 07:25
The hammer  content view version list is failing due to above bz : 
Below I am displaying the help page for clarity
hammer content-view list --help
Usage:
    hammer content-view list [OPTIONS]

Options:
 --by BY                                             Field to sort the results on
 --full-results FULL_RESULTS                         Whether or not to show all results
                                                     One of true/false, yes/no, 1/0.
 --lifecycle-environment LIFECYCLE_ENVIRONMENT_NAME  Name to search by
 --lifecycle-environment-id LIFECYCLE_ENVIRONMENT_ID  
 --name NAME                                         Name of the content view
 --noncomposite NONCOMPOSITE                         Filter out composite content views
                                                     One of true/false, yes/no, 1/0.
 --nondefault NONDEFAULT                             Filter out default content views
                                                     One of true/false, yes/no, 1/0.
 --order ORDER                                       Sort field and order, eg. 'name DESC'
 --organization ORGANIZATION_NAME                    Organization name to search by
 --organization-id ORGANIZATION_ID                   organization ID
 --organization-label ORGANIZATION_LABEL             Organization label to search by
 --page PAGE                                         Page number, starting at 1
 --per-page PER_PAGE                                 Number of results per page to return
 --search SEARCH                                     Search string
 --without WITHOUT                                   Do not include this array of content views
                                                     Comma separated list of values.
 -h, --help                                          print help

The command can be executed as follows:
hammer content-view list  --organization-id  $Some_organization_ID  

please let me know if anymore clarification is needed . thanks

**Comment by elyezer** [comment] 2015-05-04 14:37
This is not a Downstream Failure, removing the tag.

**Comment by elyezer** [comment] 2015-11-11 13:32
`hammer content-view version list` is being used on content view tests https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_contentviews.py#L839-L841 and the mentioned BZ was closed as not a bug. Closing this.

**Closed by elyezer** 2015-11-11 13:32 UTC
Labels: CLI
