### ISSUE TITLE
skip_if_open must handle resolution field of BZ

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/robottelo#4195] opened 2017-01-17 16:24 UTC
Currently a bz with resolution WONTFIX will be considered closed and test will not be skipped.

Resolutions test should be skipped:

- WONTFIX
- CANTFIX

**Comment by omaciel** [comment] 2017-01-17 18:46
I *think* that many cases where a BZ is marked as `WONTFIX` are due to an unexpected behavior that QE wants addressed. For example:

    As a User of $FOO, when I run $COMMAND I should get $RESULT1

If for example, upon testing, we identify that not only we get `$RESULT1` but also `$RESULT2`, the issue may be related to asking that only `$RESULT1` be returned and not 2 values.

If the issue is then marked as `WONTFIX` and we don't have a strong case for keeping it open, then I guess we should update our use case and tests to conform to the current behaviro:

    As a User of $FOO, when I run $COMMAND I should get $RESULT1 and $RESILT2

**Comment by rochacbruno** [comment] 2017-01-17 18:51
So if BZ 123 is CLOSED - WONTFIX, that means:
 `bz_bug_is_open(123)` should return `False` 
because that BZ cannot be considered `open` 
(as the semantic naming of our function/decorator says `is_open`,  and current behavior is right)

So in that case, it is better to get a `failure/error` and then fix the test case as @omaciel suggested.

**Comment by renzon** [comment] 2017-01-18 15:10
@rochacbruno @omaciel : I just think like you guys, but @rplevka thinks different. So I will wait for his input and we can get in some resolution.

**Comment by rplevka** [comment] 2017-01-18 15:56
@omaciel the scenario you have outlined should use `NOTABUG` resolution. `WONTFIX` is being used when the bug is valid, yet not going to get fixed (for whatever other reason) - In the recent case, dozens of old  (yet still perfectly valid) bugzillas have been closed `WONTFIX` just to get rid of the backlog.

**Comment by abalakh** [comment] 2017-01-20 09:56
@rplevka ok, take a look on another example - https://bugzilla.redhat.com/show_bug.cgi?id=1219610
We'd like to rename command to `discovery-rules` but it's never gonna be renamed. So what's the reason to keep 
```python
        if command == 'hammer' and bz_bug_is_open(1219610):
            # Adjust the discovery_rule subcommand name
            command_subcommands.discard('discovery_rule')
            command_subcommands.add('discovery-rule')
```
in code as it's never gonna work like that? `bz_bug_is_open` BZ is not open, so it returns `False`, which is logically correct and also brings our attention to outdated piece of code which should be dropped, otherwise number of such outdated workarounds could increase with time.

**Comment by rplevka** [comment] 2017-01-23 09:32
@abalakh ok, 2 comments on this one:
1. I was talking about the whole tests which are now decorated to be skipped if BZ is open. 
2. that's not an argument for my point - my point was, devs use the Bugzilla wrong. Your case is yet another example of a bug still valid, yet the bugzilla prematurely closed. What i'm suggesting is to keep the __reference__ to such cases.

That's why i'm suggesting to keep at least a reference to the BZ as e.g. 1 year later, someone hits the bug again, and will try to file it and add it to the automation again (and reinvent the wheel). 
- by having at least a nice comment in the test would most likely stop him from doing so.

**Comment by rochacbruno** [comment] 2017-01-27 15:27
Going to be handled in #4261 and #4262

**Closed by rochacbruno** 2017-01-27 15:27 UTC
