### ISSUE TITLE
Locators model error caused by unicode chars substitution.

### ISSUE THREAD

**Issue by svtkachenko** [SatelliteQE/robottelo#4072] opened 2016-12-07 10:55 UTC
When searching element by locator with substituted name with unicode chars it produce `UnicodeEncodeError`.

For now it seems like this issue does not affect any test, however it can cause problems in future.

```python
host_collection_name = gen_string('utf8')
self.activationkey.wait_until_element
(tab_locators['ak.host_collections.add.select'] % host_collection_name)
```

```python
../../../robottelo/ui/locators/model.py:290: in __mod__
    return Locator(self._strategy, self._value % other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[UnicodeEncodeError("'ascii' codec can't encode characters in position 46-55: ordinal not in range(128)") raised in repr()] SafeRepr object at 0x7f109b306b90>
args = ('xpath', "//tr/td/a[contains(., 'ﴭ샬𥫢𥚾𢥡𤅗뺂𪐚𠦐𩉁')]/parent::*/parent::*/td/input[@ng-model='hostCollection.selected']")
kwargs = {}
item = "//tr/td/a[contains(., 'ﴭ샬𥫢𥚾𢥡𤅗뺂𪐚𠦐𩉁')]/parent::*/parent::*/td/input[@ng-model='hostCollection.selected']"

    def __init__(self, *args, **kwargs):
        """Initialize Locator or LocatorDict with params
            :param args: (strategy, value) or a dict of locators
            :param kwargs: named locators
            """
        super(Locator, self).__init__(Locator)
        # _store is where (strategy, value) is stored
        self._store = [
            item for item in args if not isinstance(item, (dict, tuple))
        ]
        if len(self._store) not in (0, 2):
            raise ValueError(
                "Locator stores only 2 values e.g: Locator('xpath', '//div')"
            )
    
        # if we have a _store populated it means this instance is a locator
        # not only an empty node, so we need to store the casted value
        if len(self._store) > 1:
>           self._store[1] = LocatorValue(self._store[1])
E           UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-32: ordinal not in range(128)

../../../robottelo/ui/locators/model.py:144: UnicodeEncodeError
```
However, it works with old-fashioned `(strategy, value)` approach:
```python
            strategy, value = tab_locators['ak.host_collections.add.select']
            host_collection = self.activationkey.wait_until_element(
                (strategy, value % host_col.name))
```

**Comment by ldjebran** [comment] 2016-12-07 11:52
in model class we can fix 
```python
import six

class LocatorValue(six.text_type):
    ...

class Locator(defaultdict):
    ...

    def __repr__(self):
        """Provides representation for console in the form of:
        <|strategy=x|value=y|contains=[nested nodes]|>
        """
        msg = ["<"]
        if len(self._store) > 1:
            msg.append("strategy=%s" % self._store[0])
            msg.append("value=%s" % self._store[1])
        keys = self.keys()
        if keys:
            msg.append("contains=%s" % str(keys))
        msg.append(">")
        return u"|".join(msg).encode('utf-8')
    ...

```

**Comment by ldjebran** [comment] 2016-12-07 13:37
@omaciel @oshtaier  @rochacbruno @sghai  what do you think?

**Comment by omaciel** [comment] 2016-12-07 15:46
@ldjebran could this be resolved by explicitly updating our locators to use unicode?

```python
    "ak.host_collections.add.select": (
        By.XPATH,
        u"//tr/td/a[contains(., '%s')]"
        "/parent::*/parent::*"
        "/td/input[@ng-model='hostCollection.selected']"),
```

**Comment by ldjebran** [comment] 2016-12-07 15:56
no this will help as the problem is that LocatorValue is inheriting from str and python 2.7 any way will convert that to str
now in model module  LocatorValue looking like 
```python
class LocatorValue(str):
    ...
```

**Comment by rochacbruno** [comment] 2016-12-08 22:58
@ldjebran agreed, you have a good solution until we move to Py3

**Closed** 2016-12-19 15:11 UTC
Labels: Bug, Medium, Sprint2 05Dec16, UI
