### ISSUE TITLE
SmartVariablesTestCase - failing

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5659] opened 2017-12-07 15:12 UTC
the following tests keep consistently failing:

-  test_positive_override_default_value_from_attribute
-  test_positive_override_from_attribute
-  test_positive_update_hidden_value_in_attribute
-  test_positive_update_matcher_from_attribute

**Comment by odovzhenko** [comment] 2017-12-08 12:06
Duplicate of #5594

**Closed by odovzhenko** 2017-12-08 12:06 UTC
Labels: High, test-failure, UI

**Comment by rplevka** [comment] 2017-12-08 12:11
@odovzhenko oops :D
