### ISSUE TITLE
Automation failure : test_update_partition_table_1

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2250] opened 2015-05-18 10:51 UTC
TestNames:
tests.foreman.ui.test_partitiontable.PartitionTable.test_update_partition_table_1

Error Message
'NoneType' object has no attribute 'tag_name'
-------------------- >> begin captured logging << --------------------
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.username" by id: "login_login"
robottelo.ui.locators: DEBUG: Accessing locator "login.password" by id: "login_password"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
robottelo.ui.locators: DEBUG: Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.new" by xpath: "//a[contains(@href, '/ptables/new')]"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.name" by id: "ptable_name"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.name" by id: "ptable_name"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.layout" by id: "ptable_layout"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.layout" by id: "ptable_layout"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.os_family" by id: "ptable_os_family"
robottelo.ui.locators: DEBUG: Accessing locator "submit" by name: "commit"
robottelo.ui.locators: DEBUG: Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.ptable_name" by xpath: "//a[normalize-space(.)='%s']"
robottelo.ui.locators: DEBUG: Accessing locator "search" by id: "search"
robottelo.ui.locators: DEBUG: Accessing locator "search_button" by xpath: "//button[contains(@type,'submit')]"
robottelo.ui.locators: DEBUG: Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
robottelo.ui.locators: DEBUG: Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.ptable_name" by xpath: "//a[normalize-space(.)='%s']"
robottelo.ui.locators: DEBUG: Accessing locator "search" by id: "search"
robottelo.ui.locators: DEBUG: Accessing locator "search_button" by xpath: "//button[contains(@type,'submit')]"
robottelo.ui.locators: DEBUG: Accessing locator "ptable.name" by id: "ptable_name"
robottelo.ui.base: DEBUG: TimeoutException: Timed out waiting for element 'ptable_name' to display.
robottelo.ui.locators: DEBUG: Accessing locator "ptable.layout" by id: "ptable_layout"
robottelo.ui.base: DEBUG: TimeoutException: Timed out waiting for element 'ptable_layout' to display.
robottelo.ui.locators: DEBUG: Accessing locator "ptable.os_family" by id: "ptable_os_family"
robottelo.ui.base: DEBUG: NoSuchElementException: Could not locate element ptable_os_family.

**Comment by tkolhar** [comment] 2015-05-18 10:54
when executed locally using nosetests:
$  nosetests -c robottelo.properties -m test_update_partition_table_1 /home/tkolhar/git/robottelo/tests/foreman/ui/test_partitiontable.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@Test: Update partition table with its name, layout and OS family ... 2015-05-18 16:21:24 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-05-18 16:21:24 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
2015-05-18 16:21:24 - robottelo.ui.locators - DEBUG - Accessing locator "login.password" by id: "login_password"
2015-05-18 16:21:25 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2015-05-18 16:21:27 - robottelo.ui.locators - DEBUG - Accessing locator "notif.error" by xpath: "//div[contains(@class, 'jnotify-notification-error')]"
2015-05-18 16:21:30 - robottelo.ui.base - DEBUG - NoSuchElementException: Could not locate element //div[contains(@class, 'jnotify-notification-error')].
2015-05-18 16:21:30 - robottelo.ui.locators - DEBUG - Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
2015-05-18 16:21:30 - robottelo.ui.locators - DEBUG - Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
2015-05-18 16:21:32 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.new" by xpath: "//a[contains(@href, '/ptables/new')]"
2015-05-18 16:21:39 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.name" by id: "ptable_name"
2015-05-18 16:21:40 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.name" by id: "ptable_name"
2015-05-18 16:21:41 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.layout" by id: "ptable_layout"
2015-05-18 16:21:41 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.layout" by id: "ptable_layout"
2015-05-18 16:21:41 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.os_family" by id: "ptable_os_family"
2015-05-18 16:21:41 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2015-05-18 16:21:47 - robottelo.ui.locators - DEBUG - Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
2015-05-18 16:21:47 - robottelo.ui.locators - DEBUG - Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
2015-05-18 16:21:49 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.ptable_name" by xpath: "//a[normalize-space(.)='%s']"
2015-05-18 16:21:49 - robottelo.ui.locators - DEBUG - Accessing locator "search" by id: "search"
2015-05-18 16:21:51 - robottelo.ui.locators - DEBUG - Accessing locator "search_button" by xpath: "//button[contains(@type,'submit')]"
2015-05-18 16:21:55 - robottelo.ui.locators - DEBUG - Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
2015-05-18 16:21:55 - robottelo.ui.locators - DEBUG - Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
2015-05-18 16:21:56 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.ptable_name" by xpath: "//a[normalize-space(.)='%s']"
2015-05-18 16:21:56 - robottelo.ui.locators - DEBUG - Accessing locator "search" by id: "search"
2015-05-18 16:21:58 - robottelo.ui.locators - DEBUG - Accessing locator "search_button" by xpath: "//button[contains(@type,'submit')]"
2015-05-18 16:22:02 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.name" by id: "ptable_name"
2015-05-18 16:22:02 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.name" by id: "ptable_name"
2015-05-18 16:22:03 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.layout" by id: "ptable_layout"
2015-05-18 16:22:03 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.layout" by id: "ptable_layout"
2015-05-18 16:22:26 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.os_family" by id: "ptable_os_family"
2015-05-18 16:22:27 - robottelo.ui.locators - DEBUG - Accessing locator "submit" by name: "commit"
2015-05-18 16:22:30 - robottelo.ui.locators - DEBUG - Accessing locator "menu.hosts" by xpath: "//div[contains(@style,'static') or contains(@style,'fixed')]//a[@id='hosts_menu']"
2015-05-18 16:22:30 - robottelo.ui.locators - DEBUG - Accessing locator "menu.partition_tables" by xpath: "//div[contains(@style,'static') or contains(@style, 'fixed')]//a[@id='menu_item_ptables']"
2015-05-18 16:22:33 - robottelo.ui.locators - DEBUG - Accessing locator "ptable.ptable_name" by xpath: "//a[normalize-space(.)='%s']"
2015-05-18 16:22:33 - robottelo.ui.locators - DEBUG - Accessing locator "search" by id: "search"
2015-05-18 16:22:35 - robottelo.ui.locators - DEBUG - Accessing locator "search_button" by xpath: "//button[contains(@type,'submit')]"
2015-05-18 16:22:40 - robottelo.ui.locators - DEBUG - Accessing locator "login.gravatar" by xpath: "//img[contains(@class, 'avatar')]"
2015-05-18 16:22:40 - robottelo.ui.locators - DEBUG - Accessing locator "menu.account" by xpath: "//a[@id='account_menu']"
2015-05-18 16:22:40 - robottelo.ui.locators - DEBUG - Accessing locator "menu.sign_out" by xpath: "//a[@id='menu_item_logout']"
ok
XML: foreman-results.xml
Ran 1 test in 93.059s
OK

**Comment by jyejare** [comment] 2015-05-28 13:05
Closing as duplicate of #2301

**Closed by jyejare** 2015-05-28 13:05 UTC
Labels: Downstream Failure, UI
