### ISSUE TITLE
tests.foreman.api.test_docker/DockerContainerTestCase - fails on installing consumer cert. package

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4401] opened 2017-03-06 10:18 UTC
The whole case uses `install_katello_ca()` in `setUpClass`. Since it is being run by multiple workers, the setUpClass is executed multiple times, causing the the `install_katello_ca()` trying to install the consumer cert. package multiple times.
Since the package is already installed, the yum returns non-zero return code and the whole test fails.

proposed solution: make `install_katello_ca` method to check for the package first. If already installed, exit with success.

**Comment by lpramuk** [comment] 2017-04-06 14:58
We are lucky that it fails,
 - registering SAT to itself because of local docker host would break existing registration to dogfood and it would render any future package installations as failures

CV docker images shouldn't be tested locally - we need external docker for these tests.

**Comment by ldjebran** [comment] 2017-04-14 10:33
@lpramuk , please review the log file at the end it shows that the consumer ca are from different sat server , it seems that consumer ca was ialready installed from an other sat server 6.2.4 
http://pastebin.test.redhat.com/475474

**Comment by ldjebran** [comment] 2017-04-18 12:26
@svtkachenko @lpramuk perhaps the nightly has a different issue here, as per the log above

**Comment by lpramuk** [comment] 2017-05-05 08:04
This issue will be resolved by major refactor on behalf of #4619

**Comment by lpramuk** [comment] 2017-05-05 08:34
Closed #4019 as a duplicate of this issue

**Comment by ntkathole** [comment] 2019-06-06 07:41
Please feel free to re-open, if this still needs fixing.

**Closed by ntkathole** 2019-06-06 07:41 UTC
Labels: 6.1, 6.2, 6.3, API, Bug, CLI, UI, nightly, test-failure
