### ISSUE TITLE
UI ContentViewTestCase - newly unstubbed tests are failing

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/robottelo#4050] opened 2016-11-30 12:47 UTC
Newly unstubbed UI tests for 6.2 are failing: 

- [ ] ContentViewTestCase.test_positive_promote_composite_with_custom_content ```AssertionError: unexpectedly None```

- [ ] ContentViewTestCase.test_positive_publish_composite_with_custom_content
```AssertionError: unexpectedly None```

- [ ] ContentViewTestCase.test_positive_publish_version_changes_in_target_env
```2016-11-23 19:45:17 - nailgun.client - DEBUG - Making HTTP POST request to https://qe-sat62-rhel7.example.com/katello/api/v2/products with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"organization_id": 328, "name": "ascNahwXdCW"}.
nailgun.client - Received HTTP 500 response: {"displayMessage":"Task e4a624ba-206e-4f2e-9961-ef47283592d0: ActiveRecord::StatementInvalid: PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block\n: SELECT  \"katello_pools\".* FROM \"katello_pools\"  WHERE \"katello_pools\".\"cp_id\" = 'ff80808158939f4d015893cb3bf406c3'  ORDER BY \"katello_pools\".\"id\" ASC LIMIT 1","errors":["Task e4a624ba-206e-4f2e-9961-ef47283592d0: 
ActiveRecord::StatementInvalid: PG::Error: ERROR:  current transaction is aborted, 
commands ignored until end of transaction block\n: SELECT  \"katello_pools\".* FROM \"katello_pools\"  WHERE \"katello_pools\".\"cp_id\" = 'ff80808158939f4d015893cb3bf406c3'  ORDER BY \"katello_pools\".\"id\" ASC LIMIT 1"]}
```

the last one failed is somewhat random, nailgun failed to list product (before failing it listed a product twice successfully ?)

**Comment by ldjebran** [comment] 2016-12-01 10:33
@lpramuk, as per the latest build screen shots and logs we can assume that this due to application failure to accomplish the relevant tasks. As you can see the application failed to promote new cv to env, and to publish a new version of content view.
![contentviewtestcase-test_positive_publish_composite_with_custom_content-screenshot-2016-11-30_19_34_23](https://cloud.githubusercontent.com/assets/131553/20790583/ab429796-b7c1-11e6-8252-0063804abcb7.png)
![contentviewtestcase-test_positive_promote_composite_with_custom_content-screenshot-2016-11-30_19_22_06](https://cloud.githubusercontent.com/assets/131553/20790585/ab45ad00-b7c1-11e6-860d-5f6e55b584ae.png)
![contentviewtestcase-test_positive_publish_version_changes_in_target_env-screenshot-2016-11-30_16_53_12](https://cloud.githubusercontent.com/assets/131553/20790584/ab437ec2-b7c1-11e6-8418-5b56a924273e.png)

**Comment by ldjebran** [comment] 2016-12-01 11:36
@lpramuk 
locally tested on sat 6.2.4
```bash
(2.7) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui/test_contentview.py -v -k "test_positive_promote_composite_with_custom_content or test_positive_publish_composite_with_custom_content or test_positive_publish_version_changes_in_target_env"
========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /home/dlezz/bin/redhat/python/2.7/bin/python
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile: 
plugins: cov-2.4.0, xdist-1.15.0
collected 62 items 

tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_promote_composite_with_custom_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_publish_composite_with_custom_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_publish_version_changes_in_target_env <- robottelo/decorators/__init__.py PASSED

========================================================== 59 tests deselected ===========================================================
=============================================== 3 passed, 59 deselected in 1685.62 seconds ===============================================
(2.7) dlezz@elysion:~/projects/robottelo-fork$ 
```
now installing lastest sat build 6.2.5-1 to make a local tests

**Comment by lpramuk** [comment] 2016-12-01 13:01
It's pitty that we cannot inspect failed task details

**Comment by ldjebran** [comment] 2016-12-01 14:53
@lpramuk, The situation under 6.2.5 is like this:
```bash
(2.7) dlezz@elysion:~/projects/robottelo-fork$  py.test tests/foreman/ui/test_contentview.py -v -k "test_positive_promote_composite_with_custom_content or test_positive_publish_composite_with_custom_content or test_positive_publish_version_changes_in_target_env"
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /home/dlezz/bin/redhat/6.2.z/python/2.7/bin/python
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile: 
plugins: xdist-1.14, cov-2.3.1
collected 62 items 

tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_promote_composite_with_custom_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_publish_composite_with_custom_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_publish_version_changes_in_target_env <- robottelo/decorators/__init__.py FAILED

======================================================= FAILURES =======================================================
_______________________ ContentViewTestCase.test_positive_publish_version_changes_in_target_env ________________________

``` 
the 2 tests passed normally, these 2 tests use manifests and the failures could be caused by this also.
but the latest  test_positive_publish_version_changes_in_target_env
have a persistence failure with the same picture as jenkins job screenshot.
and definitively this is a persistent test failure.

Have to reproduce manually, to see why wrong number of argument is wrong, as from the user side we have nothing to fill, but only push a save button.

**Comment by ldjebran** [comment] 2016-12-01 14:56
@lpramuk, if this is manually reproducible we have a bug to fill, a sit pass under 6.2.4 and 6.3

**Comment by ldjebran** [comment] 2016-12-02 10:09
manually tested: registered bug:: **think this is a very urgent bug**
https://bugzilla.redhat.com/show_bug.cgi?id=1400918

@lpramuk, @omaciel , @sghai how to mark the test :: test_positive_publish_version_changes_in_target_env
when it passed under  6.2.4 and 6.3 but fail only in 6.2.5
Please note that these tests has been cherrypicked to 6.2.z branch from  master

**Comment by ldjebran** [comment] 2016-12-02 11:55
closing the issue as all work has been done on it, all the tests verified

**Closed** 2016-12-02 11:55 UTC
Labels: 6.2, review, UI

**Comment by sghai** [comment] 2016-12-02 11:59
Thanks @ldjebran for all your findings on this issue.

**Comment by ldjebran** [comment] 2016-12-02 12:03
@sghai thank you for your help too
