### ISSUE TITLE
cli.ContentViewFilterTestCase.test_positive_delete_by_org_namecontent-view - `filter delete` no longer accepts organization* parameters

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4031] opened 2016-11-24 15:19 UTC
the `--organization*` parameters are gone in `filter delete` subcommand. We might want to confirm with devs that this was by design:

```
# hammer -v -u admin -p changeme  content-view filter create --help
Usage:
    hammer content-view filter create [OPTIONS]

Options:
 --content-view CONTENT_VIEW_NAME        Content view name to search by
 --content-view-id CONTENT_VIEW_ID       content view numeric identifier
 --description DESCRIPTION               description of the filter
 --inclusion INCLUSION                   specifies if content should be included or excluded, default:
                                         inclusion=false
                                         One of true/false, yes/no, 1/0.
 --name NAME                             name of the filter
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       Organization ID to search by
 --organization-label ORGANIZATION_LABEL Organization label to search by
 --original-packages ORIGINAL_PACKAGES   add all packages without errata to the included/excluded list. (package
                                         filter only)
                                         One of true/false, yes/no, 1/0.
 --repositories REPOSITORY_NAMES         Comma separated list of values.
 --repository-ids REPOSITORY_IDS         list of repository ids
                                         Comma separated list of values.
 --type TYPE                             type of filter (e.g. rpm, package_group, erratum)
 -h, --help                              print help

```

error:
```
2016-11-02 20:07:36 - robottelo.ssh - DEBUG - >>> LANG=en_US.UTF-8  hammer -v -u admin -p changeme  content-view filter delete --organization="0LTwcq" --name="𫄿䮠𥂯𦵿𠕱𦗮𢊃𧄞ꛜ뜰" --content-view="mCvDfWohMz"
2016-11-02 20:07:38 - robottelo.ssh - DEBUG - <<< stderr
[ERROR 2016-11-02 20:07:38 Exception] Error: Unrecognised option '--organization'

See: 'hammer content-view filter delete --help'
Could not delete the filter:
  Error: Unrecognised option '--organization'
  
  See: 'hammer content-view filter delete --help'
[ERROR 2016-11-02 20:07:38 Exception] 

Clamp::UsageError (Unrecognised option '--organization'):
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/option/parsing.rb:62:in `find_option'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/option/parsing.rb:28:in `parse_options'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:53:in `parse'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:30:in `parse'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:67:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/lib/hammer_cli/abstract.rb:22:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
    /opt/theforeman/tfm/root/usr/share/gems/gems/hammer_cli-0.8.0/bin/hammer:125:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'
```

**Comment by lpramuk** [comment] 2016-11-25 13:30
@rplevka You listed output of create subcommand having --organization option.
But filter delete subcommand doesn't have such a option. Even other entities delete subcommands don't have --organization option. 
```
# hammer content-view filter delete --help
Usage:
    hammer content-view filter delete [OPTIONS]

Options:
 --content-view CONTENT_VIEW_NAME  Content view name to search by
 --content-view-id CONTENT_VIEW_ID content view numeric identifier
 --id ID                           filter identifier
 --name NAME                       Name to search by
```
Even CV deletion doesn't have that:
```
# hammer content-view delete --help
Usage:
    hammer content-view delete [OPTIONS]

Options:
 --async                       Do not wait for the task
 --id ID                       content view numeric identifier
 --name NAME                   Content view name to search by
```

**Comment by lpramuk** [comment] 2016-11-25 13:32
Not a bug. However, we need to change the tests trying to submit ```--organization``` on delete.

**Comment by rplevka** [comment] 2016-11-25 13:37
thanks for noticing.
Anyway, it is a bug and apparently a regression:

```bash
# hammer content-view delete --help
Usage:
    hammer content-view delete [OPTIONS]

Options:
 --async                       Do not wait for the task
 --id ID                       content view numeric identifier
 --name NAME                   Content view name to search by
 -h, --help                    print help
 
# hammer content-view delete --name rplevka_cv
Could not delete the content view:
  Error: Could not find organization. Some search options were missing, please see --help.

# hammer content-view delete --name rplevka_cv --organization-id 1
Could not delete the content view:
  Error: Unrecognised option '--organization-id'
  
  See: 'hammer content-view delete --help'
```

**Comment by lpramuk** [comment] 2016-11-25 13:39
We have a regression - ```Satellite 6.2``` is ok
```
# hammer -p changeme content-view delete -h create --name LP --organization-id 1
Usage:
    hammer content-view delete [OPTIONS]

Options:
 --async                                 Do not wait for the task
 --id ID                                 content view numeric identifier
 --name NAME                             Content view name to search by
 --organization ORGANIZATION_NAME        Organization name to search by
 --organization-id ORGANIZATION_ID       organization ID
 --organization-label ORGANIZATION_LABEL Organization label to search by
```

**Comment by lpramuk** [comment] 2016-11-25 13:42
hammer content-view filter delete
hammer content-view delete 
^^^ 
we need to decorate all these with https://bugzilla.redhat.com/show_bug.cgi?id=1388642

**Comment by ldjebran** [comment] 2016-12-05 17:00
@lpramuk @rplevka @sghai  hammer content view delete and filter delete already decorated by bz 1388642 and  bz 1398677
note: _1398677 set as clone of 1388642_
**think we can close this issue**

**Comment by ldjebran** [comment] 2016-12-06 07:57
let it open till next compose as #4030 that get influenced by this issue too

**Comment by ldjebran** [comment] 2016-12-13 17:02
under compose 8 same error, waiting next  compose

**Comment by lpramuk** [comment] 2017-05-05 09:31
Test is decorated now and is being skipped (bz in POST) in satellite nightly, closing.

**Closed by lpramuk** 2017-05-05 09:31 UTC
Labels: 6.3, CLI, test-failure
