### ISSUE TITLE
Fix all capsule related tests

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#3641] opened 2016-07-25 05:42 UTC
All tests related to capsule create/update/delete are failing since long, here is the exact error:

```
E           CLIFactoryError: Failed to create Proxy with data:
E           {
E             "name": "gEqdrlHAMy", 
E             "url": "https://rhel7_sat_server:19563"
E           }
E           Command "proxy create" finished with return_code 65
E           stderr contains following message:
E           [ERROR 2016-07-23 12:40:24 Exception] Unable to communicate with the Capsule: ERF12-2530 [ProxyAPI::ProxyException]: Unable to detect features ([Errno::EACCES]: Permission denied - connect(2) for "rhel7_sat_server" port 1...) for Capsule https:/rhel7_sat_server:19563/features
E           Please check the Capsule is configured and running on the host.
E           Could not create the proxy:
E             Unable to communicate with the Capsule: ERF12-2530 [ProxyAPI::ProxyException]: Unable to detect features ([Errno::EACCES]: Permission denied - connect(2) for "rhel7_sat_server" port 1...) for Capsule https://rhel7_sat_server:19563/features
E             Please check the Capsule is configured and running on the host.
```

At first place, it seems that we shouldn't create fake capsules like this. Ideally capsule should run only on 9090 and we are running on random ports. Bunch of tests are failing because of this issue.

**Comment by sghai** [comment] 2016-07-25 05:45
Failed tests:
- `tests.foreman.api.test_location.LocationTestCase.test_positive_remove_capsule	5.5 sec	54`
- `tests.foreman.api.test_location.LocationTestCase.test_positive_update_capsule	5.5 sec	54`
- ` tests.foreman.api.test_location.LocationTestCase.test_positive_create_with_capsule	5.2 sec	54`
- ` tests.foreman.cli.test_organization.OrganizationTestCase.test_positive_add_capsule_by_id	11 sec	54`
- `tests.foreman.cli.test_organization.OrganizationTestCase.test_positive_add_capsule_by_name	12 sec	54`
- `tests.foreman.cli.test_capsule.CapsuleTestCase.test_positive_refresh_features_by_id	5.2 sec	54`
- ` tests.foreman.cli.test_capsule.CapsuleTestCase.test_positive_refresh_features_by_name	5.2 sec	54`
 - `tests.foreman.cli.test_organization.OrganizationTestCase.test_positive_remove_capsule_by_id	12 sec	54`
 - `tests.foreman.cli.test_organization.OrganizationTestCase.test_positive_remove_capsule_by_name	11 sec	54`
 - `tests.foreman.cli.test_location.LocationTestCase.test_positive_add_capsule_by_id	11 sec	54`
 - `tests.foreman.cli.test_location.LocationTestCase.test_positive_add_capsule_by_name	11 sec	54`
 - `tests.foreman.cli.test_location.LocationTestCase.test_positive_remove_capsule_by_id	10 sec	54`
 - `tests.foreman.cli.test_location.LocationTestCase.test_positive_remove_capsule_by_name	11 sec	54`

**Comment by elyezer** [comment] 2016-07-26 20:06
This is mostly related to the reverse ssh tunnel we are creating in order to mock a capsule.

**Comment by rplevka** [comment] 2016-07-28 12:29
Closing this as a duplicate of https://github.com/SatelliteQE/robottelo/issues/3453

The way we mock capsule is just fine.
The problem is only on RHEL7, where SELinux comes to play.

Working on this together with @lpramuk

**Closed by rplevka** 2016-07-28 12:29 UTC
Labels: Bug, Downstream Failure, High
