### ISSUE TITLE
tests.foreman.ui.test_org.Org.test_positive_delete_bz1225588

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/robottelo#2614] opened 2015-07-24 06:13 UTC
Stacktrace
```
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/abb3bf3f/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "robottelo/common/decorators.py", line 375, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-downstream-rhel66-ui/tests/foreman/ui/test_org.py", line 332, in test_positive_delete_bz1225588
    self.assertIsNone(self.org.search(org_name))
  File "/usr/lib64/python2.7/unittest/case.py", line 994, in assertIsNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
'<selenium.webdriver.remote.webelement.WebElement object at 0x56c4910> is not None\n-------------------- >> begin captured logging << --------------------\nrobottelo.common.decorators: INFO: Bugzilla bug 1225588 not in cache. 
```

**Comment by tkolhar** [comment] 2015-07-28 09:36
tested this locally using nosetests
the test is failing 
$ nosetests -c robottelo.properties -m test_positive_delete_bz1225588 /home/tkolhar/git/robottelo/tests/foreman/ui/test_org.py
ERROR: @test: Create Organization with valid values and upload manifest.

Traceback (most recent call last):
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 288, in tearDown
    self.take_screenshot(self._testMethodName)
  File "/home/tkolhar/git/robottelo/robottelo/test.py", line 276, in take_screenshot
    directory,
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

FAIL: @test: Create Organization with valid values and upload manifest.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tkolhar/git/robottelo/robottelo/common/decorators.py", line 375, in wrapper_func
    return func(*args, **kwargs)
  File "/home/tkolhar/git/robottelo/tests/foreman/ui/test_org.py", line 332, in test_positive_delete_bz1225588
    self.assertIsNone(self.org.search(org_name))
AssertionError: <selenium.webdriver.remote.webelement.WebElement object at 0x38871d0> is not None
XML: foreman-results.xml

Ran 7 tests in 1334.856s

FAILED (errors=5, failures=1)

**Comment by jyejare** [comment] 2015-07-29 12:34
Closing as duplicate of issue #2483

**Closed by jyejare** 2015-07-29 12:34 UTC
Labels: Bug, Downstream Failure, UI
