### ISSUE TITLE
installer - InstallerParamsTestCase.test_installer_options_and_flags - needs updating

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4731] opened 2017-05-24 14:23 UTC
the following option has been added:
```
E       AssertionError: Items in the second set but not the first:
E       u'--disable-resolve-mismatches'
```

**Comment by ntkathole** [comment] 2018-01-14 09:00
Closing as dupe of Issue #5202

**Closed by ntkathole** 2018-01-14 09:00 UTC
Labels: 6.2, 6.3, Low, review
