### ISSUE TITLE
Assertion error in test_positive_synchronize_rh_product_past_sync_date

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/robottelo#6009] opened 2018-05-21 07:47 UTC
Occurs in snap4, tests.foreman.api.test_syncplan.SyncPlanSynchronizeTestCase.test_positive_synchronize_rh_product_past_sync_date

```
>               "No task was found using query '{}'".format(search_query))
E           AssertionError: No task was found using query 'resource_type = Katello::Repository and owner.login = foreman_admin and resource_id = 10'
```

**Comment by ntkathole** [comment] 2018-06-17 10:03
similar to  #5584

**Comment by san7ket** [comment] 2018-09-17 08:51
Duplicate of the above issue

**Closed by san7ket** 2018-09-17 08:51 UTC
Labels: 6.4, API, test-failure
