### ISSUE TITLE
Automation failure : TestContentViewsUI.test_cv_create_1

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2206] opened 2015-05-11 08:56 UTC
TestNames:
tests.foreman.ui.test_contentviews.TestContentViewsUI.test_cv_create_1

Error Message
unexpectedly None : Failed to find content view 10𥰦10𥰦𡟭10𥰦𡟭𦔖10𥰦𡟭𦔖𧊴蝾藤10𥰦𡟭𦔖𧊴𫐒Ᏻ10𥰦𡟭𦔖𧊴𫐒𥚼塉  from 10𥰦𡟭𦔖𧊴𫐒𥚼𩂵昄10𥰦𡟭𦔖𧊴𫐒𥚼𩂵𝒮䬴10𥰦𡟭𦔖𧊴𫐒𥚼𩂵𝒮𧫪Ẽ筎蒌駪恟10𥰦𡟭𦔖𧊴𫐒𥚼𩂵𝒮𧫪𧜨10𥰦𡟭𦔖𧊴𫐒𥚼𩂵𝒮𧫪𧜨𠾷10𥰦𡟭𦔖𧊴𫐒𥚼𩂵𝒮𧫪𧜨𠾷𓇒ᅣǈ說臌薊 org

Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/jenkins/shiningpanda/jobs/e889915e/virtualenvs/d41d8cd9/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "robottelo/common/decorators.py", line 362, in wrapper_func
    return func(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-automation-upstream-rhel66-ui/tests/foreman/ui/test_contentviews.py", line 107, in test_cv_create
    name, self.org_name))
  File "/usr/lib64/python2.7/unittest/case.py", line 1000, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)

**Comment by sghai** [comment] 2015-05-12 12:21
Duplicate of issue #2214

**Closed by sghai** 2015-05-12 12:21 UTC
Labels: Low, UI, Upstream Failures
