### ISSUE TITLE
Automation failure : test_create_ptable

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2232] opened 2015-05-14 11:37 UTC
TestNames:
tests.foreman.cli.test_partitiontable.TestPartitionTableUpdateCreate.test_create_ptable 

Error Message
70 != 0 : Failed to create object
hammer -v -u admin -p changeme --output=csv partition-table list --search="name=\"VV7xwX\"" --per-page="10000"
robottelo.common.ssh: INFO: Instantiated Paramiko client 0x4360ad0
robottelo.common.ssh: INFO: Destroying Paramiko client 0x4360ad0
robottelo.common.ssh: INFO: Destroyed Paramiko client 0x4360ad0
robottelo.common.ssh: DEBUG: <<< [ERROR 2015-05-13 15:24:14 Exception] Error: Connection refused - connect(2)
Error: Connection refused - connect(2)
[ERROR 2015-05-13 15:24:14 Exception] 

Errno::ECONNREFUSED (Connection refused - connect(2)):
    /usr/share/ruby/net/http.rb:878:in `initialize'
    /usr/share/ruby/net/http.rb:878:in `open'
    /usr/share/ruby/net/http.rb:878:in `block in connect'
    /usr/share/ruby/timeout.rb:52:in `timeout'
    /usr/share/ruby/net/http.rb:877:in `connect'
    /usr/share/ruby/net/http.rb:862:in `do_start'
    /usr/share/ruby/net/http.rb:851:in `start'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /usr/share/gems/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:279:in `call_client'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:210:in `http_call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/api.rb:160:in `call'
    /usr/share/gems/gems/apipie-bindings-0.0.11/lib/apipie_bindings/resource.rb:14:in `call'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/apipie/command.rb:43:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:185:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:270:in `send_request'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:316:in `retrieve_and_print'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:303:in `browse_collection'
    /usr/share/gems/gems/hammer_cli_foreman-0.1.4.11/lib/hammer_cli_foreman/commands.rb:288:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/lib/hammer_cli/abstract.rb:23:in `run'
    /usr/share/gems/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
    /usr/share/gems/gems/hammer_cli-0.1.4.10/bin/hammer:108:in `<top (required)>'
    /usr/bin/hammer:23:in `load'
    /usr/bin/hammer:23:in `<main>'

**Comment by tkolhar** [comment] 2015-05-14 11:38
locally when executed using nosetests, the test gets executed correctly without any error:

$ nosetests -c robottelo.properties -m test_create_ptable /home/tkolhar/git/robottelo/tests/foreman/cli/test_partitiontable.py
/usr/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin xunitmp = nose_xunitmp:XunitMP: cannot import name force_unicode
  RuntimeWarning)
@Test: Check if Partition Table can be created ... 2015-05-14 17:05:05 - robottelo - DEBUG - Running test TestPartitionTableUpdateCreate/test_create_ptable
2015-05-14 17:05:07 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2c173d0
2015-05-14 17:05:10 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2c173d0
2015-05-14 17:05:10 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2c173d0
2015-05-14 17:05:10 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv partition-table create --os-family="Solaris" --name="NUr25i" --file="/tmp/gqxSpsRh4D"
2015-05-14 17:05:12 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2c17490
2015-05-14 17:05:14 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2c17490
2015-05-14 17:05:14 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2c17490
2015-05-14 17:05:14 - robottelo.common.ssh - DEBUG - <<<
Message,Id,Name
Partition table created,38,NUr25i

2015-05-14 17:05:14 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme  partition-table info --id="38"
2015-05-14 17:05:17 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2c55d90
2015-05-14 17:05:19 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2c55d90
2015-05-14 17:05:19 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2c55d90
2015-05-14 17:05:19 - robottelo.common.ssh - DEBUG - <<<
Id:                38
Name:              NUr25i
OS Family:         Solaris
Operating systems: 

Created at:        2015/05/14 11:35:14
Updated at:        2015/05/14 11:35:14


2015-05-14 17:05:19 - robottelo.common.ssh - DEBUG - >>> [qe-sat6-rhel71.usersys.redhat.com] LANG=en_US.UTF-8 hammer -v -u admin -p changeme --output=csv partition-table list --search="name=\"NUr25i\"" --per-page="10000"
2015-05-14 17:05:22 - robottelo.common.ssh - INFO - Instantiated Paramiko client 0x2c17650
2015-05-14 17:05:23 - robottelo.common.ssh - INFO - Destroying Paramiko client 0x2c17650
2015-05-14 17:05:23 - robottelo.common.ssh - INFO - Destroyed Paramiko client 0x2c17650
2015-05-14 17:05:23 - robottelo.common.ssh - DEBUG - <<<
Id,Name,OS Family
38,NUr25i,Solaris

ok
XML: foreman-results.xml
Ran 1 test in 18.582s

OK

**Comment by elyezer** [comment] 2015-05-14 14:28
Was not able to reproduce. I have run the same test against the same machine automation did and got no failures. It seems to be some server instability because `Errno::ECONNREFUSED (Connection refused - connect(2)):`.

Will close this issue and be monitoring for that happens again.

```
$ py.test tests/foreman/cli/test_partitiontable.py -ktest_create_ptable
=================================================== test session starts ===================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
collected 6 items

tests/foreman/cli/test_partitiontable.py .

====================================== 5 tests deselected by '-ktest_create_ptable' =======================================
========================================= 1 passed, 5 deselected in 16.07 seconds =====================================

**Closed by elyezer** 2015-05-14 14:28 UTC
Labels: CLI, Downstream Failure
