### ISSUE TITLE
UI::ContentHostTestCase::test_positive_search_by_subscription_status - uses wrong setup

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#5165] opened 2017-08-18 07:46 UTC
this has been wrongly identified as a [satellite bug](https://bugzilla.redhat.com/show_bug.cgi?id=1478090).

The test is supposed to create a rhel7 host and register it using a pre-created activation key (created in the test class setup), which has 2 subscriptions attached - these subscriptions belong to 2 custom products with custom repositories.
It is true, that host is able to enable satellite tools repo and install packages from it, but we are omitting the fact, that this repo is not a real RH repo from CDN, but a repo from a dogfood server, added to our satellite in a form of a custom repository in a custom product.
The host then obviously doesn't find valid subscriptions for all its detected products (rhel-7-server) and thus its subscription status cannot be valid.
This is also perfectly visible in the logs of the test [1]:

```
2017-07-29 20:45:12 - robottelo.ssh - INFO - >>> subscription-manager register --org QmtNnXT --activationkey LBYSfmjXO --force
2017-07-29 20:45:24 - robottelo.ssh - INFO - <<< stdout
The system has been registered with ID: 100c80ff-85ce-4b79-a98d-4733286e4a6c 

Installed Product Current Status:
Product Name: Red Hat Enterprise Linux Server
Status:       Not Subscribed

Unable to find available subscriptions for all your installed products.

```

**Comment by ldjebran** [comment] 2017-08-18 12:03
This has nothing to do with CDN, when robottelo was updated to use non CDN repos many TestCases needed a care attention especially the subscriptions and errata ones.

Plus that test was supposed working when merged https://github.com/SatelliteQE/robottelo/pull/5021.

Fixed that test in https://github.com/SatelliteQE/robottelo/pull/5168

and close this bug as not a bug

**Closed** 2017-08-18 17:31 UTC
Labels: 6.2, 6.3, Bug, test-failure

**Comment by rplevka** [comment] 2017-08-19 12:39
i mentioned cdn because of the way the detected products are named:
'Red Hat Enterprise Linux Server'. if we don't use the CDN products/subs, but we create custom ones named randomly, we can't be surprised it won't match the product name advertised from RHEL - that was my point
