### ISSUE TITLE
Automate create compute resource with invalid name

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/robottelo#2263] opened 2015-05-19 11:09 UTC
please automate https://bugzilla.redhat.com/show_bug.cgi?id=1222877
create a compute resource with name like $$$$
compute resource created
however it should fail

**Comment by sghai** [comment] 2016-11-17 10:20
Closing this now as its duplicate of #2257

**Closed by sghai** 2016-11-17 10:20 UTC
Labels: UI
