### ISSUE TITLE
ui.test_variables.SmartVariablesTestCase - updating fields often not having effects

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/robottelo#4615] opened 2017-04-26 06:09 UTC
affecting:
- test_positive_update_hidden_value

```
E   AssertionError: u'0oW9vQFOIV' != u'hDbtg5vt1K'
E   - 0oW9vQFOIV
E   + hDbtg5vt1K
```
needs more investigation, does not look like a problem in a product

**Comment by svtkachenko** [comment] 2017-04-26 06:13
@rplevka Same as https://github.com/SatelliteQE/robottelo/issues/4514
PR was merged yesterday: https://github.com/SatelliteQE/robottelo/pull/4605

**Comment by svtkachenko** [comment] 2017-04-26 06:18
Closing as duplicate of #4514

**Closed by svtkachenko** 2017-04-26 06:18 UTC
Labels: 6.2, Bug, test-failure, UI
